name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name_suffix: ""
          - os: macos-latest
            asset_name_suffix: ""
          - os: windows-latest
            asset_name_suffix: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install FUSE library for Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfuse3-dev

      - name: Install Python dependencies
        run: |
          pip install pyinstaller pyqt6
          # Conditionally install pyfuse3 only on Linux.
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            pip install pyfuse3
          fi
      
      - name: Build executable with PyInstaller
        run: pyinstaller dittofs.spec

      - name: Set asset name
        id: set_name
        run: echo "ASSET_NAME=dittofs-${{ matrix.os }}${{ matrix.asset_name_suffix }}" >> $GITHUB_ENV

      - name: Rename executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: mv dist/dittofs${{ matrix.asset_name_suffix }} dist/${{ env.ASSET_NAME }}

      - name: Rename executable (Windows)
        if: runner.os == 'Windows'
        run: move dist\dittofs${{ matrix.asset_name_suffix }} dist\${{ env.ASSET_NAME }}
        
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ env.ASSET_NAME }}

